ALTER TABLE auctioneers
ADD COLUMN IF NOT EXISTS ai_preferences JSONB DEFAULT NULL;

ALTER TABLE lots
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ai_metadata JSONB DEFAULT NULL;
