'use client'
import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'

const box='rounded-3xl border border-indigo-100 bg-white p-5 sm:p-6 space-y-4'
const field='mt-1 w-full rounded-xl border border-slate-300 bg-white p-3 text-sm'
const button='min-h-11 rounded-xl bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50'
type Offer={id:string;house_id:string;kind:string;commission_percent:number|null;pickup_offer:boolean;sale_date:string|null;message:string;status:string;house:{company_name:string}}
type Request={id:string;owner_id:string;title:string;description:string;city:string;region:string;category:string;quantity:number;timeframe:string;visibility:string;radius_miles:number;status:string;moderation_status:string;offers:Offer[];intake:{id:string;status:string}|null;media:{media_id:string}[]}
type Data={requests:Request[];houses:{id:string;company_name:string}[];userId:string}
async function send(payload:unknown){const response=await fetch('/api/community/consignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again.');return result}
function Working(){return <div role="status" className="space-y-2 text-sm text-indigo-700">Working on your request<div className="h-1.5 rounded-full bg-indigo-100"><div className="h-full w-2/3 rounded-full bg-indigo-600"/></div></div>}

export function ApproximateLocation({subjectId,label='Save my approximate location'}:{subjectId:string;label?:string}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('')
 return <div className="space-y-2"><button className={button} disabled={busy} type="button" onClick={()=>{setBusy(true);setMessage('');if(!navigator.geolocation){setBusy(false);setMessage('Location is unavailable in this browser.');return}navigator.geolocation.getCurrentPosition(async position=>{try{await send({operation:'location',subject_id:subjectId,latitude:position.coords.latitude,longitude:position.coords.longitude});setMessage('Approximate location saved for distance matching.')}catch(err){setMessage((err as Error).message)}finally{setBusy(false)}},()=>{setMessage('Location permission was not granted. You can still choose all approved houses.');setBusy(false)},{enableHighAccuracy:false,timeout:15000,maximumAge:300000})}}>{label}</button><p className="text-xs text-slate-500">Coordinates are rounded to roughly a kilometer and used privately for matching. Your exact address is not requested.</p>{busy&&<Working/>}{message&&<p role="status" className="text-sm text-indigo-700">{message}</p>}</div>
}

export function Consignments({requestId}:{requestId?:string}){
 const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[login,setLogin]=useState(false),[mode,setMode]=useState('mine'),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setBusy(true);setError('');try{const query=requestId?`id=${requestId}`:`mode=${mode}`;const response=await fetch(`/api/community/consignments?${query}`,{cache:'no-store'});const result=await response.json();if(response.status===401){setLogin(true);return}if(!response.ok)throw new Error(result.error);setData(result)}catch(err){setError((err as Error).message)}finally{setBusy(false)}},[mode,requestId])
 useEffect(()=>{void load()},[load])
 return <main className="mx-auto max-w-5xl space-y-6 px-4 py-10 sm:px-6"><header className="space-y-4"><Link href="/feed" className="text-sm font-semibold text-indigo-700">← Community</Link><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Imagine This · Consignments</p><h1 className="font-serif text-4xl text-slate-950">Sell with an auction house.</h1><p className="max-w-2xl text-slate-600">From a single find to a whole estate: share what you have, compare responses, and choose the house that fits.</p></header>{busy&&<Working/>}{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-indigo-50 p-4 text-indigo-800">{notice}</p>}{login&&<Link className={`${button} inline-block`} href="/login">Sign in to get started</Link>}
 {data&&<>{!requestId&&<><div className="flex gap-3"><button className={button} aria-pressed={mode==='mine'} onClick={()=>setMode('mine')}>My requests</button>{data.houses.length>0&&<button className={button} aria-pressed={mode!=='mine'} onClick={()=>setMode('available')}>House inbox</button>}</div>{mode==='mine'&&<ConsignmentForm userId={data.userId} onSaved={async pending=>{setNotice(pending?'Your request is waiting for moderation.':'Your request is ready for eligible houses to view.');await load()}}/>}{mode!=='mine'&&data.houses.map(h=><section className={box} key={h.id}><h2 className="font-semibold">Local leads for {h.company_name}</h2><ApproximateLocation subjectId={h.id} label="Set this house’s approximate location"/></section>)}</>}
 {!busy&&!data.requests.length&&<p className="py-6 text-slate-500">{requestId?'This request is unavailable.':'No requests to show yet.'}</p>}{data.requests.map(request=>requestId?<RequestDetails key={request.id} request={request} data={data} refresh={load}/>:<article key={request.id} className={box}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold"><Link href={`/consign/${request.id}`}>{request.title}</Link></h2><span className="text-xs capitalize text-indigo-700">{request.moderation_status==='pending'?'Awaiting review':request.status}</span></div><p className="line-clamp-3 text-sm text-slate-600">{request.description}</p><p className="text-sm text-slate-500">{request.city}, {request.region} · {request.quantity} item{request.quantity===1?'':'s'} · {request.category}</p><Link className="inline-block font-semibold text-indigo-700" href={`/consign/${request.id}`}>View request & responses →</Link></article>)}</>}
 </main>
}

function ConsignmentForm({userId,onSaved}:{userId:string;onSaved:(pending:boolean)=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[files,setFiles]=useState<File[]>([]),[local,setLocal]=useState(false)
 return <details className={box}><summary className="cursor-pointer text-lg font-semibold">Share an item or estate</summary><form className="space-y-4" onSubmit={async event=>{event.preventDefault();const element=event.currentTarget;const form=new FormData(element);setBusy(true);setError('');try{const media_ids=[];for(const file of files){const upload=new FormData();upload.set('file',file);const response=await fetch('/api/community/media',{method:'POST',body:upload});const media=await response.json();if(!response.ok)throw new Error(media.error);media_ids.push(media.id)}const result=await send({operation:'create',title:form.get('title'),description:form.get('description'),category:form.get('category'),city:form.get('city'),region:form.get('region'),quantity:Number(form.get('quantity')),timeframe:form.get('timeframe'),visibility:local?'local':'all',radius_miles:Number(form.get('radius')||25),media_ids});element.reset();setFiles([]);setLocal(false);await onSaved(result.moderation_status==='pending')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>
 <label className="block text-sm">What are you selling?<input className={field} name="title" required minLength={3} maxLength={120} placeholder="Vintage coin collection or family estate"/></label><label className="block text-sm">Description<textarea className={field} name="description" required minLength={10} maxLength={4000} rows={4} placeholder="Condition, approximate size of the collection, and what you know about it"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Category<input className={field} name="category" required maxLength={40}/></label><label className="text-sm">Approximate item count<input className={field} name="quantity" type="number" required min={1} max={100000} defaultValue={1}/></label><label className="text-sm">City<input className={field} name="city" required maxLength={80}/></label><label className="text-sm">State / region<input className={field} name="region" required maxLength={80}/></label></div><label className="block text-sm">Preferred timeframe<input className={field} name="timeframe" required maxLength={200} placeholder="Within the next two months"/></label><label className="block text-sm">Photos (up to 10)<input type="file" className="mt-2 block max-w-full text-sm" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const next=Array.from(e.target.files??[]);if(next.length>10){setError('Choose up to ten photos.');e.target.value='';setFiles([])}else setFiles(next)}}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={local} onChange={e=>setLocal(e.target.checked)}/> Only show to houses near me</label>{local&&<div className="space-y-3 rounded-xl bg-indigo-50 p-4"><ApproximateLocation subjectId={userId}/><label className="block text-sm">House search radius (miles)<input className={field} type="number" min={1} max={500} defaultValue={25} name="radius"/></label></div>}<p className="text-xs text-slate-500">Only eligible approved auction houses can view your request. A claim is an expression of interest; you choose whether to accept.</p>{busy&&<Working/>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}<button className={button} disabled={busy}>Share consignment request</button>
 </form></details>
}

function RequestDetails({request:r,data,refresh}:{request:Request;data:Data;refresh:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const owner=r.owner_id===data.userId,accepted=r.offers.find(o=>o.status==='accepted'),house=accepted&&data.houses.some(h=>h.id===accepted.house_id)
 async function action(payload:unknown){setBusy(true);setError('');try{await send(payload);await refresh();setNotice('Saved.')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <><article className={box}><h2 className="font-serif text-3xl">{r.title}</h2><p className="text-sm capitalize text-indigo-700">{r.status} · {r.moderation_status==='pending'?'Awaiting moderation':r.visibility==='local'?`Houses within ${r.radius_miles} miles`:'All approved houses'}</p><p className="whitespace-pre-wrap text-slate-700">{r.description}</p><p className="text-sm text-slate-500">{r.city}, {r.region} · {r.category} · {r.quantity} items · {r.timeframe}</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{r.media.map(m=><img key={m.media_id} className="aspect-square w-full rounded-xl object-cover" alt={`Consignment photo for ${r.title}`} src={`/api/community/consignments?mode=media&id=${r.id}&media_id=${m.media_id}`}/>)}</div>{owner&&r.status==='open'&&<button className="text-sm underline" disabled={busy} onClick={()=>void action({operation:'withdraw',id:r.id})}>Withdraw this request</button>}{!owner&&<details><summary className="cursor-pointer text-sm text-slate-500">Report this request</summary><form className="mt-2 space-y-2" onSubmit={e=>{e.preventDefault();void action({operation:'report',id:r.id,reason:new FormData(e.currentTarget).get('reason')})}}><textarea className={field} name="reason" aria-label="Report reason" required minLength={10} maxLength={2000}/><button className={button} disabled={busy}>Send report</button></form></details>}</article>
 {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{notice&&<p role="status" className="text-sm text-indigo-700">{notice}</p>}{busy&&<Working/>}
 {!owner&&r.status==='open'&&data.houses.length>0&&<form className={box} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({operation:'offer',id:r.id,house_id:f.get('house'),kind:f.get('kind'),commission_percent:f.get('commission')===''?null:Number(f.get('commission')),pickup_offer:f.get('pickup')==='on',sale_date:f.get('date')||null,message:f.get('message')})}}><h3 className="text-xl font-semibold">Respond as an auction house</h3><label className="block text-sm">House<select className={field} name="house">{data.houses.map(h=><option key={h.id} value={h.id}>{h.company_name}</option>)}</select></label><label className="block text-sm">Response<select className={field} name="kind"><option value="quote">Send a quote</option><option value="claim">Claim interest (seller must accept)</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Commission percentage<input className={field} name="commission" type="number" min={0} max={100} step="0.1"/></label><label className="text-sm">Expected sale date<input className={field} type="date" name="date"/></label></div><label className="flex gap-2 text-sm"><input type="checkbox" name="pickup"/>We can offer pickup</label><label className="block text-sm">Details for the seller<textarea className={field} required minLength={5} maxLength={2000} name="message" rows={3}/></label><button className={button} disabled={busy}>Send response</button></form>}
 <section className={box}><h3 className="text-xl font-semibold">House responses</h3>{!r.offers.length&&<p className="text-sm text-slate-500">No responses yet.</p>}{r.offers.map(o=><article className="space-y-3 border-t border-indigo-100 pt-4" key={o.id}><h4 className="font-semibold">{o.house.company_name}</h4><p className="text-xs capitalize text-indigo-700">{o.kind} · {o.status}</p><p className="whitespace-pre-wrap text-sm">{o.message}</p><p className="text-sm text-slate-500">{o.commission_percent!==null?`${o.commission_percent}% commission`:'Commission to be agreed'} · {o.pickup_offer?'Pickup offered':'Pickup to be discussed'}{o.sale_date?` · Expected sale: ${o.sale_date}`:''}</p>{owner&&r.status==='open'&&o.status==='pending'&&<button className={button} disabled={busy} onClick={()=>void action({operation:'accept',id:o.id})}>Accept offer & create intake</button>}{!owner&&o.status==='pending'&&<button className="text-sm underline" disabled={busy} onClick={()=>void action({operation:'withdraw-offer',id:o.id})}>Withdraw response</button>}</article>)}</section>
 {r.intake&&<section className={box}><h3 className="text-xl font-semibold">Consignment intake</h3><p className="text-sm capitalize">Status: {r.intake.status}</p>{house&&r.intake.status!=='completed'&&<button className={button} disabled={busy} onClick={()=>void action({operation:'intake',id:r.intake!.id,status:({planned:'received',received:'catalogued',catalogued:'completed'} as Record<string,string>)[r.intake!.status]})}>Mark {({planned:'received',received:'catalogued',catalogued:'completed'} as Record<string,string>)[r.intake.status]}</button>}{house&&<Link className="block text-sm font-semibold text-indigo-700" href={`/org/quick-list?consignment=${r.id}`}>Prepare lots in Quick List →</Link>}{r.intake.status==='completed'&&<form className="space-y-3 border-t pt-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action({operation:'rate',id:r.intake!.id,stars:Number(f.get('stars')),body:f.get('body')})}}><h4 className="font-semibold">Rate this consignment experience</h4><label className="block text-sm">Rating<select className={field} name="stars">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} star{n===1?'':'s'}</option>)}</select></label><textarea name="body" aria-label="Consignment review" className={field} maxLength={1000}/><button className={button} disabled={busy}>Save rating</button></form>}</section>}</>
}

export function ConsignmentModeration(){
 const [rows,setRows]=useState<{id:string;title:string;description:string;reason?:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState('')
 const load=useCallback(async()=>{const response=await fetch('/api/community/consignments?mode=moderation',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setRows([...data.pending,...data.reports.map((r:{request_id:string;reason:string;request:{title:string;description:string}})=>({id:r.request_id,...r.request,reason:r.reason}))])},[])
 useEffect(()=>{void load().catch(err=>setError(err.message))},[load])
 return <section className={box}><h2 className="text-xl font-semibold">Consignment moderation</h2><label className="block text-sm">Decision explanation<input className={field} value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label>{error&&<p role="alert" className="text-rose-700">{error}</p>}{!rows.length&&<p className="text-sm text-slate-500">No consignment requests need review.</p>}{rows.map((r,index)=><article key={r.id+index} className="space-y-3 border-t pt-3"><h3 className="font-semibold">{r.title}</h3><p className="text-sm">{r.description}</p>{r.reason&&<p className="text-sm text-rose-700">Report: {r.reason}</p>}<div className="flex gap-3">{[true,false].map(approve=><button className={button} key={String(approve)} disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);try{await send({operation:'review',id:r.id,approve,reason});await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>{approve?'Approve / keep':'Hide'}</button>)}</div></article>)}</section>
}
