'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

const button='rounded-xl bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50 min-h-11'
const field='w-full rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-900'
type Row={is_house_staff?:boolean;id:string;body:string;asker_id?:string;author_id?:string;photo_request?:boolean;answer?:string;answered_at?:string;media_id?:string;pinned?:boolean;moderation_status:string;created_at:string;profile?:{handle:string;display_name:string}|null}
type Data={rows:Row[];auction:{id:string;title:string;status:string;ends_at:string};settings:{slow_seconds:number;locked:boolean};canManage:boolean;userId:string|null}
async function write(payload:unknown) {
  const response=await fetch('/api/community/discussions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})
  const data=await response.json();if(!response.ok) throw new Error(data.error||'Please try again.');return data
}
function Progress(){return <div role="status" className="space-y-2 py-3 text-sm text-indigo-700">Loading the conversation<div className="h-1.5 rounded-full bg-indigo-100"><div className="h-full w-2/3 rounded-full bg-indigo-600"/></div></div>}

export function AuctionDiscussion({lotId,auctionId}:{lotId?:string;auctionId:string}) {
  const [enabled,setEnabled]=useState(false),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[body,setBody]=useState(''),[photo,setPhoto]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const load=useCallback(async()=>{
    const query=new URLSearchParams(lotId?{mode:'questions',lot_id:lotId}:{mode:'room',auction_id:auctionId})
    const response=await fetch(`/api/community/discussions?${query}`,{cache:'no-store'});const value=await response.json()
    if(!response.ok) throw new Error(value.error||'Could not load the conversation.');setData(value)
  },[lotId,auctionId])
  useEffect(()=>{let cancelled=false;fetch('/api/community/status',{cache:'no-store'}).then(r=>r.json()).then(async flag=>{if(!cancelled && flag.enabled){setEnabled(true);await load()}}).catch(err=>{if(!cancelled)setError(err.message)});return()=>{cancelled=true}},[load])
  useEffect(()=>{
    if(!enabled)return
    const client=createClient();const table=lotId?'community_questions':'community_room_messages'
    const channel=client.channel(`discussion:${lotId??auctionId}`).on('postgres_changes',{event:'*',schema:'public',table,filter:lotId?`lot_id=eq.${lotId}`:`auction_id=eq.${auctionId}`},()=>void load().catch(err=>setError(err.message))).subscribe()
    const interval=setInterval(()=>void load().catch(err=>setError(err.message)),30000)
    return()=>{clearInterval(interval);void client.removeChannel(channel)}
  },[enabled,lotId,auctionId,load])
  if(!enabled)return null
  const open=!!lotId || (!!data && (data.auction.status==='live' || (data.auction.status==='ended' && Date.parse(data.auction.ends_at)>Date.now()-86400000)))
  async function send(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await write(lotId?{operation:'ask',lot_id:lotId,body,photo_request:photo}:{operation:'chat',auction_id:auctionId,body});setBody('');setPhoto(false);setNotice(result.moderation_status==='pending'?'Your message is waiting for review.':lotId?'Your question is posted.':'Message sent.');await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <section className="my-8 space-y-5 rounded-3xl border border-indigo-100 bg-white p-5 sm:p-6" aria-label={lotId?'Ask the auctioneer':'Auction chat'}>
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-serif text-2xl text-slate-950">{lotId?'Ask the auctioneer':'Auction chat'}</h2><button className="text-sm text-indigo-700 underline" onClick={()=>void load().catch(err=>setError(err.message))}>Refresh</button></div>
    <p className="text-sm text-slate-600">{lotId?'Ask about condition, dimensions, or request a closer photo. Answers are shared with everyone.':`Chat is open while the auction is live and for 24 hours afterward. Slow mode: ${data?.settings.slow_seconds??5} seconds.`}</p>
    {!data && !error && <Progress/>}{error && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{notice && <p role="status" className="rounded-xl bg-indigo-50 p-3 text-sm text-indigo-800">{notice}</p>}
    {data && <>
      {!lotId && data.canManage && <form className="flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-3" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await write({operation:'room-settings',auction_id:auctionId,slow_seconds:Number(form.get('slow')),locked:form.get('locked')==='on'});await load()}catch(err){setError((err as Error).message)}}}><label className="text-sm">Slow mode (seconds)<input className={`${field} max-w-28`} name="slow" type="number" min={5} max={300} defaultValue={data.settings.slow_seconds}/></label><label className="text-sm"><input type="checkbox" name="locked" defaultChecked={data.settings.locked}/> Pause chat</label><button className={button}>Save chat settings</button></form>}
      <div className="space-y-4" aria-live="polite">{(lotId?data.rows:[...data.rows].reverse()).map(row=><DiscussionItem key={row.id} row={row} question={!!lotId} me={data.userId} manager={data.canManage} refresh={load}/>)}{!data.rows.length && <p className="py-4 text-sm text-slate-500">{lotId?'No questions yet. Be the first to ask.':'No messages yet. Say hello when chat opens.'}</p>}</div>
      {!data.userId?<Link href="/login" className="inline-block text-sm font-semibold text-indigo-700">Sign in to {lotId?'ask a question':'join the chat'} →</Link>:!open?<p className="text-sm text-slate-500">Chat opens when this auction goes live and closes 24 hours after it ends.</p>:!lotId && data.settings.locked && !data.canManage?<p className="text-sm text-slate-500">The auction house has paused chat.</p>:<form onSubmit={send} className="space-y-3 border-t border-indigo-100 pt-5"><label className="block text-sm font-medium">{lotId?'Your question':'Your message'}<textarea className={`${field} mt-2`} rows={lotId?3:2} required maxLength={lotId?2000:1000} value={body} onChange={e=>setBody(e.target.value)}/></label>{lotId && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={photo} onChange={e=>setPhoto(e.target.checked)}/> Request a condition photo</label>}<button className={button} disabled={busy||!body.trim()}>{busy?'Sending…':lotId?'Ask question':'Send message'}</button></form>}
    </>}
  </section>
}

function DiscussionItem({row,question,me,manager,refresh}:{row:Row;question:boolean;me:string|null;manager:boolean;refresh:()=>Promise<void>}) {
  const [answer,setAnswer]=useState(row.answer??''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[report,setReport]=useState(false),[reason,setReason]=useState('')
  const own=(row.asker_id??row.author_id)===me
  async function person(action: 'blocks'|'mutes'){setBusy(true);setError('');try{const response=await fetch(`/api/community/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_id:row.asker_id??row.author_id,active:true})});const result=await response.json();if(!response.ok)throw new Error(result.error);await refresh()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  async function action(payload:unknown){setBusy(true);setError('');try{await write(payload);await refresh();setReport(false)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  async function reply(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{let media_id=row.media_id??null;if(file){const form=new FormData();form.set('file',file);const response=await fetch('/api/community/media',{method:'POST',body:form});const uploaded=await response.json();if(!response.ok)throw new Error(uploaded.error||'Photo upload failed.');media_id=uploaded.id}await write({operation:'answer',id:row.id,body:answer,media_id});setFile(null);await refresh()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
  return <article className="space-y-3 rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap gap-2 text-xs text-slate-500">{row.profile?<Link className="font-semibold text-indigo-700" href={`/u/${row.profile.handle}`}>{row.profile.display_name}</Link>:<span>Community member</span>}{row.is_house_staff&&<span className="font-semibold text-indigo-700">House staff</span>}<time dateTime={row.created_at}>{new Date(row.created_at).toLocaleString()}</time>{row.pinned&&<span>Pinned by house</span>}{row.photo_request&&<span>Photo requested</span>}{row.answer&&<span className="font-semibold text-emerald-700">Answered by house</span>}{row.moderation_status==='pending'&&<span>Awaiting review</span>}</div><p className="whitespace-pre-wrap break-words text-sm text-slate-800">{row.body}</p>{row.answer&&<div className="space-y-3 rounded-xl bg-indigo-50 p-4"><p className="text-xs font-semibold text-indigo-700">Auction house answer</p><p className="whitespace-pre-wrap text-sm">{row.answer}</p>{row.media_id&&<img className="max-h-96 rounded-xl object-contain" src={`/api/community/discussions?mode=photo&id=${row.id}`} alt="Condition photo supplied by the auction house"/>}</div>}
    {manager&&question&&row.moderation_status==='approved'&&<details><summary className="cursor-pointer text-sm text-indigo-700">{row.answer?'Update house answer':'Answer this question'}</summary><form onSubmit={reply} className="mt-3 space-y-3"><textarea aria-label="House answer" required maxLength={4000} value={answer} onChange={e=>setAnswer(e.target.value)} className={field}/><label className="block text-sm">Condition photo (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)} className="block max-w-full text-xs"/></label><button className={button} disabled={busy}>Publish answer</button></form></details>}
    {me&&<div className="flex flex-wrap gap-4 text-xs text-slate-500">{question&&manager&&<button disabled={busy} onClick={()=>void action({operation:'pin',id:row.id,active:!row.pinned})}>{row.pinned?'Unpin':'Pin question'}</button>}{(manager||own)&&<button disabled={busy} onClick={()=>void action({operation:question?'hide-question':'hide-message',id:row.id})}>Hide</button>}{!own&&<><button onClick={()=>setReport(v=>!v)}>Report</button><button disabled={busy} onClick={()=>void person('mutes')}>Mute member</button><button disabled={busy} onClick={()=>void person('blocks')}>Block member</button></>}</div>}
    {report&&<form onSubmit={e=>{e.preventDefault();void action({operation:'report',id:row.id,type:question?'question':'message',reason})}} className="space-y-2"><label className="text-sm">Reason for report<textarea className={field} required minLength={10} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={button} disabled={busy}>Send report</button></form>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}
  </article>
}

export function QuestionInbox() {
  const [questions,setQuestions]=useState<{id:string;body:string;lot_id:string;photo_request:boolean;lots:{title:string}}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true)
  const load=useCallback(async()=>{setBusy(true);setError('');try{const response=await fetch('/api/community/discussions?mode=inbox',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setQuestions(data.questions)}catch(err){setError((err as Error).message)}finally{setBusy(false)}},[])
  useEffect(()=>{void load()},[load])
  return <section className="space-y-4 rounded-3xl border border-indigo-100 bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Unanswered lot questions</h2><button className="text-sm text-indigo-700 underline" onClick={()=>void load()}>Refresh</button></div>{busy&&<Progress/>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}{!busy&&!questions.length&&<p className="text-sm text-slate-500">You’re caught up. New questions will appear here.</p>}{questions.map(q=><article key={q.id} className="space-y-2 border-t pt-3"><p className="text-sm font-semibold">{q.lots.title}</p><p className="text-sm text-slate-600">{q.body}</p>{q.photo_request&&<p className="text-xs text-indigo-700">Condition photo requested</p>}<Link href={`/lots/${q.lot_id}`} className="inline-block text-sm font-semibold text-indigo-700">View lot & answer →</Link></article>)}</section>
}

export function DiscussionModeration() {
  const [rows,setRows]=useState<{id:string;type:'question'|'message';body:string;report_id?:string;reason?:string}[]>([]),[error,setError]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{const response=await fetch('/api/community/discussions?mode=moderation',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setRows([...data.questions.map((r:Row)=>({...r,type:'question'})),...data.messages.map((r:Row)=>({...r,type:'message'})),...data.reports.map((r:{id:string;question_id:string|null;message_id:string|null;reason:string;question:{body:string}|null;message:{body:string}|null})=>({id:r.question_id??r.message_id,type:r.question_id?'question':'message',body:r.question?.body??r.message?.body??'Content unavailable',report_id:r.id,reason:r.reason}))])},[])
  useEffect(()=>{void load().catch(err=>setError(err.message))},[load])
  return <section className="space-y-4 rounded-3xl border border-indigo-100 bg-white p-6"><h2 className="text-xl font-semibold">Questions & chat moderation</h2><label className="block text-sm">Decision explanation<input className={field} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000}/></label>{error&&<p role="alert" className="text-rose-700">{error}</p>}{!rows.length&&<p className="text-sm text-slate-500">No discussion items need review.</p>}{rows.map(row=><article className="space-y-3 border-t pt-4" key={row.report_id??row.id}><p className="whitespace-pre-wrap text-sm">{row.body}</p>{row.reason&&<p className="text-sm text-rose-700">Report: {row.reason}</p>}<div className="flex gap-3">{[true,false].map(approve=><button key={String(approve)} className={button} disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);setError('');try{await write({operation:'review',id:row.id,type:row.type,approve,report_id:row.report_id??null,reason});await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>{approve?'Approve / keep':'Hide'}</button>)}</div></article>)}</section>
}
