'use client'
import {useCallback,useEffect,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
const box='space-y-4 rounded-3xl border border-indigo-100 bg-white p-5 sm:p-6',button='min-h-11 rounded-xl bg-indigo-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50',field='w-full rounded-xl border border-slate-300 bg-white p-3 text-sm'
type Message={id:string;author_id:string;body:string;moderation_status:string;created_at:string;media:{media_id:string}[]}
type Conversation={id:string;person_a:string;person_b:string;unread:number;other:{user_id:string;handle:string;display_name:string}|null;members:{user_id:string;last_read_at:string}[]}
type Data={conversations:Conversation[];messages:Message[];next:string|null;userId:string}
async function send(payload:unknown){const response=await fetch('/api/community/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again.');return data}
function Progress(){return <div role="status" className="space-y-2 text-sm text-indigo-700">Updating your messages<div className="h-1.5 rounded-full bg-indigo-100"><div className="h-full w-2/3 rounded-full bg-indigo-600"/></div></div>}
export function MessageButton({recipientId,houseId}:{recipientId:string;houseId?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter()
 return <span className="inline-flex flex-col gap-2"><button className={button} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await send({operation:'start',recipient_id:recipientId,house_id:houseId??null});router.push(`/messages/${result.id}`)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>Message</button>{error&&<span role="alert" className="max-w-xs text-xs text-rose-700">{error}</span>}</span>
}
export function Messages({conversationId}:{conversationId?:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[login,setLogin]=useState(false),[body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[handle,setHandle]=useState(''),[before,setBefore]=useState<string|null>(null)
 const router=useRouter()
 const load=useCallback(async()=>{const params=new URLSearchParams({...conversationId?{id:conversationId}:{},...before?{before}:{}});const response=await fetch(`/api/community/messages?${params}`,{cache:'no-store'});const result=await response.json();if(response.status===401){setLogin(true);return}if(!response.ok)throw new Error(result.error);setData(result);if(conversationId && !before && document.visibilityState==='visible')await send({operation:'read',id:conversationId})},[conversationId,before])
 useEffect(()=>{void load().catch(err=>setError(err.message))},[load])
 useEffect(()=>{if(!conversationId)return;const client=createClient();const channel=client.channel('private-messages:'+conversationId).on('postgres_changes',{event:'*',schema:'public',table:'community_messages',filter:`conversation_id=eq.${conversationId}`},()=>void load().catch(err=>setError(err.message))).subscribe();const interval=setInterval(()=>{if(document.visibilityState==='visible')void load().catch(err=>setError(err.message))},15000);return()=>{clearInterval(interval);void client.removeChannel(channel)}},[conversationId,load])
 const conversation=data?.conversations[0]
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const media_ids=[];for(const file of files){const form=new FormData();form.set('file',file);const response=await fetch('/api/community/media',{method:'POST',body:form});const media=await response.json();if(!response.ok)throw new Error(media.error);media_ids.push(media.id)}await send({operation:'send',id:conversationId,body,media_ids});setBody('');setFiles([]);setBefore(null);await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <main className="mx-auto max-w-4xl space-y-6 px-4 py-10"><header className="space-y-4"><Link href={conversationId?'/messages':'/feed'} className="text-sm font-semibold text-indigo-700">← {conversationId?'Messages':'Community'}</Link><h1 className="font-serif text-4xl">{conversationId?conversation?.other?.display_name??'Conversation':'Your messages'}</h1><p className="text-sm text-slate-600">Private conversations with houses and fellow collectors. Your message preferences and blocks apply here.</p></header>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}{login&&<Link className={`${button} inline-block`} href="/login">Sign in to view messages</Link>}{!data&&!error&&!login&&<Progress/>}
 {!conversationId&&data&&<><form className={box} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/community/profiles?handle='+encodeURIComponent(handle.replace(/^@/,'')));const result=await response.json();if(!response.ok||!result.profiles?.[0])throw new Error('That collector profile is unavailable.');const started=await send({operation:'start',recipient_id:result.profiles[0].user_id});router.push(`/messages/${started.id}`)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><label className="block space-y-2 text-sm">Message a collector by handle<input className={field} required pattern="@?[a-z0-9_]{3,30}" value={handle} onChange={e=>setHandle(e.target.value.toLowerCase())} placeholder="@collector_handle"/></label><button className={button} disabled={busy}>Start conversation</button></form>{!data.conversations.length&&<p className="py-6 text-slate-500">No conversations yet. Open a collector or house profile to send a message.</p>}{data.conversations.map(c=><Link key={c.id} href={`/messages/${c.id}`} className={`${box} block`}><span className="flex items-center justify-between gap-3"><span className="font-semibold">{c.other?.display_name??'Community member'}</span>{c.unread>0&&<span className="rounded-full bg-indigo-700 px-3 py-1 text-xs text-white">{c.unread} unread</span>}</span><span className="text-sm text-slate-500">Open conversation →</span></Link>)}</>}
 {conversationId&&data&&!conversation&&<p className="text-slate-500">This conversation is unavailable.</p>}
 {conversationId&&data&&conversation&&<><div className="flex flex-wrap gap-3">{before&&<button className={button} onClick={()=>setBefore(null)}>Latest messages</button>}{data.next&&<button className={button} onClick={()=>setBefore(data.next)}>Older messages</button>}<button className="text-sm text-indigo-700 underline" onClick={()=>void load().catch(err=>setError(err.message))}>Refresh</button><Link href="/settings/community" className="text-sm text-indigo-700 underline">Message preferences</Link><button className="text-sm text-slate-500 underline" onClick={async()=>{try{const target=conversation.person_a===data.userId?conversation.person_b:conversation.person_a;const response=await fetch('/api/community/blocks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_id:target,active:true})});if(!response.ok)throw new Error('Could not block this member.');await load()}catch(err){setError((err as Error).message)}}}>Block member</button></div><section className="space-y-4" aria-label="Conversation messages">{!data.messages.length&&<p className="py-6 text-sm text-slate-500">Start the conversation below.</p>}{data.messages.map(m=><PrivateMessage key={m.id} message={m} own={m.author_id===data.userId} read={conversation.members.some(member=>member.user_id!==data.userId&&Date.parse(member.last_read_at)>=Date.parse(m.created_at))} refresh={load}/>)}</section>{!before&&<form className={box} onSubmit={submit}><label className="block space-y-2 text-sm">Your message<textarea className={field} rows={4} required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="block space-y-2 text-sm">Photos (up to 4)<input className="block max-w-full" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{const selected=Array.from(e.target.files??[]);if(selected.length>4){setError('Choose up to four photos.');e.target.value='';setFiles([])}else setFiles(selected)}}/></label>{busy&&<Progress/>}<button className={button} disabled={busy||!body.trim()}>Send message</button></form>}</>}
 </main>
}
function PrivateMessage({message:m,own,read,refresh}:{message:Message;own:boolean;read:boolean;refresh:()=>Promise<void>}){
 const [report,setReport]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 return <article className={`${box} ${own?'ml-6 !bg-indigo-50':'mr-6'}`}><p className="text-xs text-slate-500">{own?'You':'Member'} · {new Date(m.created_at).toLocaleString()} · {m.moderation_status==='pending'?'Waiting for moderation':own?(read?'Read':'Sent'):''}</p><p className="whitespace-pre-wrap break-words text-sm">{m.body}</p><div className="grid grid-cols-2 gap-3">{m.media.map(photo=><img className="w-full rounded-xl" key={photo.media_id} alt="Photo attached to this private message" src={`/api/community/messages?mode=media&message_id=${m.id}&media_id=${photo.media_id}`}/>)}</div><div className="flex gap-4 text-xs text-slate-500">{own&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await send({operation:'hide',id:m.id});await refresh()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>Remove message</button>}<button onClick={()=>setReport(v=>!v)}>{own?'Request moderation review':'Report message'}</button></div>{report&&<form className="space-y-2" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await send({operation:'report',id:m.id,reason:new FormData(e.currentTarget).get('reason')});setReport(false)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><label className="block text-xs">An admin can view this reported message. Explain why it needs review.<textarea className={field} name="reason" minLength={5} maxLength={2000} required/></label><button className={button} disabled={busy}>Send for review</button></form>}{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}</article>
}
export function MessageModeration(){
 const [reports,setReports]=useState<{id:string;reason:string;message:{body:string}}[]>([]),[error,setError]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const response=await fetch('/api/community/messages?mode=moderation',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setReports(data.reports)},[])
 useEffect(()=>{void load().catch(err=>setError(err.message))},[load])
 return <section className={box}><h2 className="text-xl font-semibold">Reported private messages</h2><p className="text-xs text-slate-500">Only the reported message is available here.</p><label className="block text-sm">Decision explanation<input className={field} value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="text-rose-700">{error}</p>}{!reports.length&&<p className="text-sm text-slate-500">No private messages need review.</p>}{reports.map(r=><article key={r.id} className="space-y-3 border-t pt-4"><p className="whitespace-pre-wrap text-sm">{r.message.body}</p><p className="text-xs text-rose-700">Report: {r.reason}</p><div className="flex gap-3">{[true,false].map(approve=><button key={String(approve)} className={button} disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);try{await send({operation:'review',report_id:r.id,approve,reason});await load()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}>{approve?'Approve / keep':'Hide'}</button>)}</div></article>)}</section>
}
